name: Dispatch Event Workflow2 Json

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions UI
  push:
    paths:
      - 'path/to/json_files/**'  # Specify the path where JSON files are stored
    branches:
      - main  # Specify your branch

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Check for JSON file changes
        id: check_files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep ".json" || echo "no json changes"

      - name: Repository Dispatch
        if: steps.check_files.outputs.files != 'no json changes'
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use PAT instead of GITHUB_TOKEN
          repository: 'yuunlimm/test-workflow'  # Replace with your processor repo
          event-type: 'json-change-detected'   # Custom event type used in the target repo
          client-payload: '{"commit_hash" : "${{ github.sha }}" }'  # Send the commit hash as a payload
