name: Trigger Dispatch Event

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions UI

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repository Dispatch with Payload
        run: |
          gh api --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/yuunlimm/test-workflow/dispatches \
          -f "event_type=json-change-detected" \
          -F "client_payload[unit]=false" \
          -F "client_payload[integration]=true"
