name: Dispatch Event to Processor Repo

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions UI
  push:
    paths:
      - 'jsons/**'  # Specify the path where JSON files are stored
    branches:
      - main  # or your relevant branch

jobs:
  dispatch_event:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

#      - name: Dispatch Event to Processor Repo
#        uses: peter-evans/repository-dispatch@v3.0.0
#        with:
#          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use PAT instead of GITHUB_TOKEN
#          repository: 'yuunlimm/test-workflow'   # Replace with your target repo (e.g., 'user/repository')
#          event-type: 'json-change-detected'    # The custom event type you're using in the target repo workflow
#          client-payload: '{"commit_hash": "${{ github.sha }}"}'  # Send the commit hash as payload

      # Conditionally Dispatch Event to Processor Repo if Differences Found
      - name: Dispatch Event to Processor Repo
        uses: codex-/return-dispatch@feat/improve_retry_strategy
        id: return_dispatch
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use PAT instead of GITHUB_TOKEN
          repo: test-workflow   # Replace with your target repo (e.g., 'user/repository')
          owner: yuunlimm
          ref: main
          workflow: integration-tests.yaml  # Name of the workflow file to trigger
          workflow_inputs: '{"commit_hash": "${{ github.sha }}"}'


