name: Dispatch Event to Processor Repo

on:
  workflow_dispatch:  # Allows manual trigger from the GitHub Actions UI
  push:
    paths:
      - 'jsons/**'  # Specify the path where JSON files are stored
    branches:
      - main  # or your relevant branch

jobs:
  dispatch_event:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Dispatch Event to Processor Repo
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use a Personal Access Token (PAT) for private repos if needed
          repository: 'yuunlimm/test-workflow'  # Target repo (e.g., your processor repo)
          event-type: 'json-change-detected'
          client-payload: '{"commit_hash": "${{ github.sha }}"}'  # Send the commit hash as payload
