name: Trigger Test Workflow

# This enables manual triggering via the GitHub Actions UI
on:
  workflow_dispatch:  # Allows you to manually run this workflow from the Actions tab

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Get Mock Commit Hash
        run: echo "COMMIT_HASH=mock-commit-hash" >> $GITHUB_ENV
        # Here we're just mocking a commit hash as an example

      - name: Trigger Repository Dispatch
        run: |
          gh api -X POST repos/yuunlimm/test-workflow/dispatches \
            -f event_type=json-change-detected \
            -f client_payload='{"commit_hash":"${{ env.COMMIT_HASH }}"}' \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
