name: Trigger Test Workflow

on:
  workflow_dispatch:  # Allows you to manually run this workflow from the Actions tab

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Set GH_TOKEN Environment Variable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api -X POST repos/yuunlimm/test-workflow/dispatches \
            -f event_type=json-change-detected \
            -f client_payload='{"commit_hash":"random-hash"}'
